title: "Operating Systems 2021-1 (OS211)"
description: "Hello"
author: "ghifariaulia"
address: "Tangsel"
sitemap: "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb: "https://ghifariaulia.github.io/os211/"
urlgithub: "https://github.com/ghifariaulia/os211/"
urlghpage: "https://ghifariaulia.github.io/os211/"
keywords: "jekyll, testing"
github: [metadata]